from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from time import sleep
s=Service(executable_path='./chromedriver')
driver = webdriver.Chrome(service=s)
driver.get('https://qzone.qq.com/')
driver.switch_to.frame('login_frame')
a_tag=driver.find_element_by_id("switcher_plogin")
a_tag.click()
userName_tag=driver.find_element_by_id('u')
password_tag=driver.find_element_by_id('p')
sleep(1)
userName_tag.send_keys('1183316726')
sleep(1)
password_tag.send_keys('A2241412ljq@')
sleep(1)
btn=driver.find_element_by_id('login_button')
btn.click()
sleep(3)
driver.quit()